### Schema

CREATE DATABASE photoShare_db;
USE photoShare_db;

SELECT * FROM users;


CREATE TABLE burgers(
	id int AUTO_INCREMENT NOT NULL,
	burger_name VARCHAR(30) NOT NULL,
	devoured BOOLEAN DEFAULT FALSE,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);